src/basket/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.home, name="home"),
    path('addphone/<str:phone_id>/', views.addphone, name="addphone"),
    path('removephone/<str:phone_id>/', views.removephone, name="removephone"),
]

src/phone_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('web.urls')),
    path('users/', include('users.urls')),
    path('phones/', include('phones.urls')),
    path('basket/', include('basket.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

src/phones/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'phones'

urlpatterns = [
    path('<str:id>/', views.phonedetail, name="detail"),
]

src/users/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.loginView, name="login"),
    path('logout/', views.logoutView, name="logout"),
    path('register/', views.registerView, name="register"),
]

src/web/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.home, name="home"),
    path('shop/', views.shop, name="shop"),
    path('contactus/', views.contactus, name="contactus"),
]

src/basket/models.py
from django.db import models
from django.contrib.auth.models import User
from phones.models import Phone
from django.utils import timezone

MAX_ORDER_COUNT = 100


class Basket(models.Model):
    user = models.ForeignKey(User, verbose_name='کاربر', on_delete=models.CASCADE)
    phone = models.ForeignKey(Phone, verbose_name='تلفن همراه', on_delete=models.CASCADE)
    count = models.PositiveSmallIntegerField(
        verbose_name='تعداد',
        default=1,
        choices=[(i, i) for i in range(1, MAX_ORDER_COUNT + 1)]
    )
    add_datetime = models.DateTimeField(verbose_name='زمان اضافه کردن', default=timezone.now, editable=False)

    def __str__(self):
        return f'user:{self.user}, phone:{self.phone}, count:{self.count}'

src/basket/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from basket.models import Basket
from phones.models import Phone


@login_required
def home(request):
    items = list(Basket.objects.filter(user=request.user).order_by("add_datetime"))

    if request.method == 'POST':
        for item in items:
            item.count = int(request.POST.get(item.phone.id))
            if item.count <= 0:
                item.delete()       # deleting from database
                items.remove(item)  # deleting from items list
            else:
                item.save()

    context = {
        'basket_items': items,
        'items_count': len(items),
        'total_price': sum([item.phone.price * item.count for item in items])
    }

    return render(request, 'basket.html', context=context)


@login_required
def addphone(request, phone_id):
    temp_item = Basket.objects.filter(user=request.user, phone=phone_id)

    if temp_item:   # adding to counter if item already in basket
        temp_item = temp_item.get()
        temp_item.count += 1
        temp_item.save()
    else:
        phone = Phone.objects.get(id=phone_id)
        if phone.is_available:
            Basket.objects.create(user=request.user, phone=phone)

    return redirect('basket:home')


@login_required
def removephone(request, phone_id):
    get_object_or_404(Basket, user=request.user, phone=phone_id).delete()
    return redirect('basket:home')

src/templates/basket.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>سبد خرید</title>
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap_basket.min.css' %}">
    <!-- main css -->
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
    <script src="{% static 'assets/js/all.js' %}"></script>
</head>

<body>
    <section class="pt-5 pb-5">
        <div class="container">
            <div class="row w-100">
                <div class="col-lg-12 col-md-12 col-12">
                    <h3 class="display-5 mb-2 text-center">سبد خرید</h3>
                    <p class="mb-5 text-center">
                        تعداد محصولات در سبد خرید شما : <i class="text-info font-weight-bold">{{items_count}}</i></p>
                    <form action="" method="post" class="table-responsive">
                        {% csrf_token %}
                        <table id="shoppingCart" class="table table-condensed">
                            <thead>
                                <tr>
                                    <th style="width:auto"class="text-left">محصول</th>
                                    <th style="width:20%"class="text-center">(تومان) قیمت</th>
                                    <th style="width:10%" class="text-center">تعداد</th>
                                    <th style="width:10%"class="text-center">حذف</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in basket_items %}
                                    <tr>
                                        <td data-th="Product">
                                            <div class="row">
                                                <div class="col-md-2 text-center">
                                                    <a href="{% url 'phones:detail' id=item.phone.id %}" target="_blank">
                                                        <img src={{item.phone.image.url}} alt="s20"
                                                        class="img-fluid d-none d-md-block rounded mb-2 shadow ">
                                                    </a>
                                                </div>
                                                <div class="col-md-9 text-left mt-sm-2">
                                                    <h4>{{item.phone.brand}} {{item.phone.name}}</h4>
                                                </div>
                                            </div>
                                        </td>
                                        <td data-th="Price" class="text-center font-weight-bold js__price" style="padding-top: 5.2%;">{{item.phone.price}}</td>
                                        <td data-th="Quantity" style="padding-top: 4%;">
                                            <input type="number" name={{item.phone.id}} class="form-control form-control-lg text-center" value={{item.count}}
                                                >
                                        </td>
                                        <td class="actions" data-th="" style="padding-top: 4.5%;">
                                            <div class="text-center">
                                                <a class="btn btn-white bg-white btn-md mb-2 text-danger"
                                                href="{% url 'basket:removephone' phone_id=item.phone.id %}">
                                                    <i class="fas fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <div class="text-center">
                            <button class="btn btn-white bg-white btn-md mb-1 text-success"
                                type="submit" name='save' value="save" {% if items_count == 0 %} disabled {% endif %}>
                                ذخیره تغییرات
                                <i class="fas fa-sync"></i>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="row mt-1 d-flex align-items-center justify-content-center">
                <div class="col-10 col-sm-6  mx-auto">
                    <div class="d-flex flex-row-reverse">
                        <h4 class="mt-2 ml-2">:جمع مبالغ خرید</h4>
                        <h3 class="mt-2 ml-2 js__price">{{total_price}}</h3>
                    </div>
                    <button class="btn btn-primary mb-4 btn-lg px-5" {% if items_count == 0 %} disabled {% endif %}>تایید و پرداخت</a>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 mb-3 mb-m-1 order-md-1 text-md-left">
                    <a href="{% url 'web:shop' %}">
                        <i class="fas fa-arrow-left mr-2"></i>بازگشت به فروشگاه</a>
                </div>
            </div>
        </div>
    </section>

    <script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
    <!-- bootstrap js -->
    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
    <!-- script js -->
    <script src="{% static 'assets/js/script.js' %}"></script>
    <script src="{% static 'assets/js/price-fix.js' %}"></script>
</body>

</html>

src/templates/beforehome.html
<html lang="fa">

<head>
    <meta charset="UTF-8">
    <title>صفحه ی اصلی</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/bootstrap-grid.min.css">
    <!-- main css -->
    <link rel="stylesheet" href="css/main.css">
    <link rel="icon" sizes="32x32" href="favicon.ico">
    <script src="js/all.js"></script>
</head>

<body class="rtl">
    <div class="container-fluid my-1">
        <button class="btn d-inline-block d-md-none " data-toggle="modal" data-target="#exampleModalLong">
            <span>
                <i class="fas fa-search"></i>
            </span>
        </button>
        <!-- modal -->
        <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog"
            aria-labelledby="exampleModalLongTitle" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content border-0 mt-5" style="background: transparent;">
                    <div class="modal-body mx-auto">
                        <form action="" class="form-group ">
                            <div class="input-group mb-3">
                                <div class="input-group-prepend ">
                                    <button class="btn" type="submit" id="" style="background: #ffffff;">
                                        <span>
                                            <i class="fas fa-search"></i>
                                        </span>
                                    </button>
                                </div>
                                <input type="search" class="form-control p-4" placeholder=""
                                    aria-label="Example text with button addon" aria-describedby="">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- endmodal -->
        <div class="navbar justify-content-start d-inline-block">
            <button class="btn py-0 m-0 px-3 sign-btn">
                <a class="nav-item nav-link d-inline-block text-white" href="#">ثبت نام</a>
            </button>
            <button class="btn py-0 m-0 px-3 login-btn">
                <a class="nav-item nav-link d-inline-block" href="#">ورود</a>
            </button>
        </div>
        <!-- socials -->
        <div class="nav-icons float-left d-md-inline-block d-none ">
            <a href="#" class="nav-icon">
                <i class="fab fa-facebook"></i>
            </a>
            <a href="#" class="nav-icon">
                <i class="fab fa-twitter"></i>
            </a>
            <a href="#" class="nav-icon">
                <i class="fab fa-instagram"></i>
            </a>
        </div>
        <!-- socialsend -->
    </div>
    <!-- menu =============================== -->
    <div>
        <nav class="navbar navbar-dark navbar-expand-sm" style="background-color: var(--mainred);">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mycollapse"
                    aria-controls="mycollapse" aria-expanded="false" aria-label="Toggle Navigation">
                    <span class="navbar-icon">
                        <i class="fas fa-bars"></i>
                    </span>
                </button>
                <div class="collapse navbar-collapse" id="mycollapse">
                    <div class="navbar-nav mx-auto">
                        <a class="nav-item nav-link active" href="#">خانه</a>
                        <a class="nav-item nav-link " href="#">فروشگاه</a>
                        <a class="nav-item nav-link" href="#">ارتباط با ما</a>
                    </div>
                    <form class="form-inline my-2 my-lg-0 d-md-inline-block d-none">
                        <input class="form-control mr-sm-2 mt-3" type="text" placeholder="جست‌وجو">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">جست‌وجو</button>
                    </form>
                </div>
            </div>
        </nav>
    </div>

    <!-- end menu ================================= --> 
    <!-- carousel -->
    <div class="container">
        <div class="row my-5">
            <div class="col-md-10 mx-auto">
                <div id="carousel-example" class="carousel slide justify-content-center" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carousel-example" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel-example" data-slide-to="1"></li>
                        <li data-target="#carousel-example" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="images/39009-Galaxy_Note20_01_610_710.jpg" class="img-fluid float-left" alt="First slide" />
                            <div class="carousel-caption text-dark d-none d-md-block">
                                <h3>Galaxy_Note20</h3>
                                <p><a class="btn btn-clear btn-sm btn-min-block" href="landing.html">جزییات بیشتر</a>
                                </p>
                            </div>
                            
                        </div>
                        <div class="carousel-item">
                            <img src="images/39030-Galaxy_M51_08_610_710.jpg" class="img-fluid float-left" alt="Second slide" />
                            <div class="carousel-caption  float-right text-left text-dark d-none d-md-block">
                                <h3>Galaxy_M51</h3>
                                <p><a class="btn btn-clear btn-sm btn-min-block" href="#">جزییات بیشتر</a></p>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <img src="images/39067-Galaxy_S20_FE_01_610_710.jpg" class="img-fluid float-left" alt="Third slide" />
                            <div class="carousel-caption  float-right text-left text-dark d-none d-md-block">
                                <h3>Galaxy_S20</h3>
                                <p><a class="btn btn-clear btn-sm btn-min-block" href="#">جزییات بیشتر</a></p>
                            </div>
                        </div>
                    </div>

                    <!-- Left and right controls -->
                    <a class="left carousel-control-prev" href="#carousel-example" role="button"
                        data-slide="prev">
                        <span class="fa fa-arrow-left " aria-hidden="true"></span>
                    </a>
                    <a class="right carousel-control-next" href="#carousel-example" role="button"
                        data-slide="next">
                        <span class="fa fa-arrow-right" aria-hidden="true"></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!--Contact Section -->
    <section class="contact py-5 my-5" id="contact">
        <div class="container">
            <div class="row">
                <div class="col-8 mx-auto col-md-6">
                    <form>
                        <div class="form-group">
                            <input type="email" class="form-control contact-input p-3" placeholder="ایمیل">
                            <button type="submit" class="btn btn-outline-secondary btn-block contact-btn">عضویت در
                                خبرنامه</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!--EndContact Section -->
    <!--Footer-->
    <footer class="footer pt-3 pb-5 mb-0">
        <div class="container">
            <div class="connect ml-3">
                <p>
                    <span class="footer-icon"><i class="fas fa-map-marker-alt"></i></span>
                    <span>مازندران , ساری</span>
                </p>
                <p>
                    <span class="footer-icon"><i class="fas fa-mobile-alt"></i></span>
                    <span>09331234567</span>
                </p>
                <p>
                    <span class="footer-icon"><i class="fas fa-phone"></i></span>
                    <span>01133313456</span>
                </p>
            </div>
            <hr class="bg-white">
            <div class="footer-icons d-flex justify-content-around">
                <a href="#" class="footer-icon">
                    <i class="fab fa-facebook"></i>
                </a>
                <a href="#" class="footer-icon">
                    <i class="fab fa-twitter"></i>
                </a>
                <a href="#" class="footer-icon">
                    <i class="fab fa-instagram"></i>
                </a>
                <a href="#" class="footer-icon">
                    <i class="fab fa-linkedin"></i>
                </a>
                <a href="#" class="footer-icon">
                    <i class="fab fa-google-plus"></i>
                </a>
            </div>
        </div>

    </footer>
    <!-- End Footer-->
    <script src="js/jquery-3.3.1.min.js"></script>
    <!-- bootstrap js -->
    <script src="js/bootstrap.bundle.min.js"></script>
    <!-- script js -->
    <script src="js/script.js"></script>
    <script src="js/custom.js"></script>
</body>

</html>

src/templates/contact-us.html
<html lang="fa">

<head>
    <meta charset="UTF-8">
    <title>ارتباط با ما</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/bootstrap-grid.min.css">
    <!-- main css -->
    <link rel="stylesheet" href="css/main.css">
    <link rel="icon" sizes="32x32" href="favicon.ico">
    <script src="js/all.js"></script>
</head>
<body>
    <div class="container contactus">
        <div class="row">
            <div class="col-md-3">
                <div class="contact-info">
                    <img src="images/email-20-512.png" class="img-fluid" alt="">
                    <h2>ارتباط با ما</h2>
                    <h4>لطفا پیشنهادات و انتقادات خود را با ما درمیان بگذارید.</h4>
                </div>
            </div>
            <div class="col-md-9">
                <div class="contact-form">
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="fname">نام</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" placeholder="نام" name="" id="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="lname">نام خوانوادگی</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" placeholder="نام خوانوادگی" name="" id="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="email">ایمیل</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" placeholder="ایمیل" name="" id="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="comment">نظر</label>
                        <div class="col-sm-10">
                            <textarea class="form-control" name="" id="" rows="5"></textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-10 col-sm-offset-2">
                            <button type="submit" class="btn btn-default">ارسال</button>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>


    <script src="js/jquery-3.3.1.min.js"></script>
    <!-- bootstrap js -->
    <script src="js/bootstrap.bundle.min.js"></script>
    <!-- script js -->
    <script src="js/script.js"></script>
    <script src="js/custom.js"></script>
</body>
</html>

src/templates/contactus.html
{% load static %}
<html lang="fa">

<head>
    <meta charset="UTF-8">
    <title>ارتباط با ما</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap-grid.min.css' %}">
    <!-- main css -->
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
    <script src="{% static 'assets/js/all.js' %}"></script>
</head>
<body>
    <div class="container contactus">
        <div class="row">
            <div class="col-md-3">
                <div class="contact-info">
                    <img src="{% static 'assets/images/email-20-512.png' %}" class="img-fluid" alt="">
                    <h2>ارتباط با ما</h2>
                    <h4>لطفا پیشنهادات و انتقادات خود را با ما درمیان بگذارید.</h4>
                </div>
            </div>
            <div class="col-md-9">
                <div class="contact-form">
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="fname">نام</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" placeholder="نام" name="" id="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="lname">نام خوانوادگی</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" placeholder="نام خوانوادگی" name="" id="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="email">ایمیل</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" placeholder="ایمیل" name="" id="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="comment">نظر</label>
                        <div class="col-sm-10">
                            <textarea class="form-control" name="" id="" rows="5"></textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-10 col-sm-offset-2">
                            <button type="submit" class="btn btn-default">ارسال</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                    <a href="{% url 'web:home' %}" class="text-info">
                        بازگشت به صفحه اصلی <i class="fas fa-arrow-left mr-2"></i></a>
            </div>
        </div>

    </div>


    <script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
    <!-- bootstrap js -->
    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
    <!-- script js -->
    <script src="{% static 'assets/js/script.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>
</body>
</html>

src/templates/login.html
{% load static %}
<html lang="fa">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap-grid.min.css' %}">
    <!-- main css -->
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
    <script src="{% static 'assets/js/all.js' %}"></script>
</head>

<body style="background: var(--main1);">
    <div class="container">
        <div class="row">
            <div id="contentdiv" class="contcustom">
                <span class="fa fa-spinner bigicon"></span>
                <h2>ورود</h2>
                {{ form.non_field_errors }}
                {% if error %}
                <span class='text-danger'>
                  {{error}}
                </span>
                {% endif %}
                <form method="POST">
                    {% csrf_token %}
                    {{ form.username }}
                    {{ form.username.errors }}
                    {{ form.password }}
                    {{ form.password.errors }}
                    <button type="submit" id="button1" class="btn btn-grad"><span
                            class="fa fa-check med"></span></button>
                </form>
                <a href="{% url 'users:register' %}" class="text-info">تاکنون ثبت نام نکرده‌اید؟</a>
            </div>
        </div>
    </div>
    <script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
    <!-- bootstrap js -->
    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
    <!-- script js -->
    <script src="{% static 'assets/js/script.js' %}"></script>
</body>

</html>

src/templates/register.html
{% load static %}
<html lang="fa">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap-grid.min.css' %}">
    <!-- main css -->
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
    <script src="{% static 'assets/js/all.js' %}"></script>
</head>

<body style="background: var(--main1);">
    <div class="container">
        <div class="row">
            <div id="contentdiv" class="contcustom">
                <span class="fa fa-spinner bigicon"></span>
                <h2>عضویت</h2>
                {% if error %}
                <span class='text-danger'>
                    {{error}}
                </span>
                {% endif %}
                {{ form.non_field_errors }}
                <form method="POST">
                    {% csrf_token %}
                    {{ form.username }}
                    {{ form.username.errors }}
                    {{ form.password1 }}
                    {{ form.password1.errors }}
                    {{ form.password2 }}
                    {{ form.password2.errors }}
                    <button type="submit" id="button1" class="btn btn-grad"><span
                            class="fa fa-check med"></span></button>
                </form>
                <a href="{% url 'users:login' %}" class="text-info">قبلا ثبت‌ نام کرده‌اید؟</a>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
    <!-- bootstrap js -->
    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
    <!-- script js -->
    <script src="{% static 'assets/js/script.js' %}"></script>
</body>

</html>

src/templates/sign.html
<html lang="fa">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/bootstrap-grid.min.css">
    <!-- main css -->
    <link rel="stylesheet" href="css/main.css">
    <script src="js/all.js"></script>
</head>

<body style="background: var(--main1);">
    <div class="container">
        <div class="row">
            <div id="contentdiv" class="contcustom">
                <span class="fa fa-spinner bigicon"></span>
                <h2>عضویت</h2>
                <div>
                    <input id="username" type="text" placeholder="نام کاربری">
                    <input id="password" type="password" placeholder="رمز عبور">
                    <input id="password" type="password" placeholder="تکرار رمز عبور">
                    <button id="button1" class="btn btn-grad"><span
                            class="fa fa-check med"></span></button>
                </div>
            </div>
        </div>
    </div>
    <script src="js/jquery-3.3.1.min.js"></script>
    <!-- bootstrap js -->
    <script src="js/bootstrap.bundle.min.js"></script>
    <!-- script js -->
    <script src="js/script.js"></script>
</body>

</html>